name: Lint platform modules
on:
  push:
    branches: [main]
    paths: ['aws/**/*.yaml', 'aws/**/*.yml']
  pull_request:
    paths: ['aws/**/*.yaml', 'aws/**/*.yml']
permissions:
  contents: read
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install cfn-lint
      - run: cfn-lint 'aws/modules/**/template.yaml'
